export interface DefaultRule {
    num: number;
    text: string;
    penalty: string;
}

export const DEFAULT_RULES: DefaultRule[] = [
    { num: 1,  text: 'Threats of Violence — Threatening to harm a member IRL or encouraging self-harm.', penalty: '.banish (Permanent removal)' },
    { num: 2,  text: 'Doxxing — Posting another member\'s real name, address, workplace, or other personal info without consent.', penalty: '.banish and .blacklist' },
    { num: 3,  text: 'NSFW Content — Sending explicit images, videos, or stickers.', penalty: '.banish (Permanent removal)' },
    { num: 4,  text: 'Harassment — Repeatedly targeting a member after being told to stop.', penalty: '.deport and .blacklist' },
    { num: 5,  text: 'Hate Speech — Using slurs or targeting protected identities.', penalty: '.deport (3-day ban) and .blacklist' },
    { num: 6,  text: 'Racial or Religious Discrimination — Using slurs or targeting members based on race, ethnicity, or religious beliefs.', penalty: '.blacklist and immediate .deport' },
    { num: 7,  text: 'Unsolicited DMs — Messaging members privately without consent.', penalty: '.blacklist and immediate .deport' },
    { num: 8,  text: 'Leaking Information — Sharing screenshots of group chats, phone numbers, or private data outside of the group.', penalty: '.banish (Permanent removal)' },
    { num: 9,  text: 'Underage Users — Members confirmed to be under 13 or under the group\'s age limit.', penalty: 'Immediate .exile and report to platform' },
    { num: 10, text: 'Scamming — Tricking members into sending coins via .transfer.', penalty: '.blacklist and Full refund from offender\'s wallet to victim' },
    { num: 11, text: 'Call Bombing — Adding members to a call repeatedly after they decline/hang up.', penalty: '.blacklist and .deport' },
    { num: 12, text: 'Political or Sectarian Debate — Engaging in heavy political or sensitive religious arguments that cause group division.', penalty: '15-minute .mute and .deport' },
    { num: 13, text: 'Defamation — Spreading false rumors about a citizen\'s .history.', penalty: 'Level 2 .seize paid to the victim as Damages' },
    { num: 14, text: 'Spreading Fake News — Sharing unverified news, false alerts, or misinformation.', penalty: '.labor and Level 1 .seize' },
    { num: 15, text: 'Identity Theft — Changing .alias to match another citizen\'s name.', penalty: '.labor and Level 2 .seize' },
    { num: 16, text: 'Profile Picture Violation — Using an offensive, NSFW, or impersonating photo as your WhatsApp profile picture while in the group.', penalty: '.labor and forced .exile until the photo is changed' },
    { num: 17, text: 'Mentioning the Group in Status — Posting group-specific drama, screenshots, or the group link on your personal status without permission.', penalty: '.blacklist and 30-minute .mute' },
    { num: 18, text: 'Status Mention Spam — Tagging the group or members in your status repeatedly to bait drama.', penalty: '.blacklist and 30-minute .mute' },
    { num: 19, text: 'Exploit Abuse — Using bugs in the bot to duplicate coins, items, or bypass cooldowns.', penalty: '.seize (Triple the exploited amount) and .blacklist' },
    { num: 20, text: 'Financial Tax Evasion — Using glitches to avoid the automatic .tax.', penalty: '.seize (Double the tax amount) and .labor' },
    { num: 21, text: 'Using Multiple Numbers — Entering the group with two or more accounts to manipulate voting or avoid .tax.', penalty: 'Permanent .blacklist of all associated numbers and seizure of all wallets to the .vault' },
    { num: 22, text: 'Selling Accounts — Buying/selling/trading group accounts or bot currency for real money.', penalty: '.banish and seizure of all wallets to .vault' },
    { num: 23, text: 'Marriage Fraud — Marrying just to steal a partner\'s coins.', penalty: 'Forced .divorce and .seize (All stolen coins returned and fine)' },
    { num: 24, text: 'Gambling Without License — Running unapproved .bet or .lottery games that aren\'t logged by the bot.', penalty: 'Level 3 .seize and .labor' },
    { num: 25, text: 'Bribe Solicitation — An admin asking for coins to dismiss a case.', penalty: 'Immediate .impeach vote and .seize of admin wallet to .vault' },
    { num: 26, text: 'Draft Dodging — Leaving the group to escape an active .labor or .dare timer.', penalty: 'Automatic .blacklist and all coins moved to .vault upon re-entry' },
    { num: 27, text: 'Vote Manipulation — Bribing or threatening members to influence .impeach, .trial, or poll results.', penalty: '.blacklist and voiding of votes' },
    { num: 28, text: 'Begging / Solicitation — Repeatedly asking members for coins, money, gifts, or follows.', penalty: '10-minute .mute and Level 1 .seize' },
    { num: 29, text: 'Bot Warfare — Using other bots to trigger or crash the group bot.', penalty: '.banish (Permanent removal)' },
    { num: 30, text: 'Raid Participation — Coordinating or joining mass-joins to disrupt this or other groups.', penalty: '.banish and .blacklist' },
    { num: 31, text: 'Adding Bots Without Approval — Inviting external bots or automation numbers to the group.', penalty: '.banish and .blacklist' },
    { num: 32, text: 'Changing Group Info — Changing the group name, icon, or description without being authorized.', penalty: 'Immediate .exile and .blacklist' },
    { num: 33, text: 'Resetting Invite Links — Revoking/changing the group invite link if you\'re not lead admin.', penalty: 'Immediate .exile and .blacklist' },
    { num: 34, text: 'Mass Add/Kick — Adding or removing 5+ members at once without admin order.', penalty: '.blacklist and Level 3 .seize' },
    { num: 35, text: 'Disrespecting Admins — Arguing against a final admin decision or using insults toward the leadership team.', penalty: '.blacklist and Level 3 .seize' },
    { num: 36, text: 'Treason — Proposing an .impeach vote against an admin without a valid reason.', penalty: '.blacklist and Level 3 .seize' },
    { num: 37, text: 'Admin Impersonation — Setting name or bio to mimic group authority.', penalty: '.blacklist and Level 2 .seize' },
    { num: 38, text: 'Impersonating the Bot — Setting name/bio to mimic bot commands or responses to confuse members.', penalty: '.blacklist and Level 2 .seize' },
    { num: 39, text: 'Perjury — Lying while acting as a .witness in a trial.', penalty: '.blacklist and .labor' },
    { num: 40, text: 'False Indictment — Suing someone with zero proof or fake evidence.', penalty: 'The accuser faces the original punishment intended for the defendant and .seize' },
    { num: 41, text: 'Contempt of Court — Insulting the bot or disrupting an active trial.', penalty: '5-minute .mute and Level 1 .seize' },
    { num: 42, text: 'Encouraging Rule Breaking — Telling other members to ignore bot punishments or bypass group laws.', penalty: '.blacklist and Level 2 .seize' },
    { num: 43, text: 'Ghosting Duty — A .jury member who enters a trial but refuses to vote.', penalty: 'Level 1 .seize' },
    { num: 44, text: 'Looping Arguments — Restarting a closed case or settled argument after admin ruling.', penalty: '10-minute .mute and .labor' },
    { num: 45, text: 'Illegal Immigration — Staying as a Tourist after .visa expires.', penalty: 'Immediate .deport until a .visa is purchased' },
    { num: 46, text: 'Refusal to Verify — Failure to use the .id or .visa command when requested by an admin during a security check.', penalty: '.exile (Kick)' },
    { num: 47, text: 'Inactivity — Failure to send a message or use a command for over 7 days.', penalty: 'Automatic .exile (Kick) to free up space for active citizens' },
    { num: 48, text: 'Unauthorized Link Sending — Posting any URL or group invite without prior approval.', penalty: '.blacklist and Level 2 .seize' },
    { num: 49, text: 'Link Shilling — Sending invites to other groups without permission.', penalty: '.blacklist and Level 3 .seize' },
    { num: 50, text: 'Illegal Advertising — Promoting products, services, or social media handles without admin consent.', penalty: '.blacklist and Level 3 .seize' },
    { num: 51, text: 'Community/Channel Spam — Promoting WhatsApp Communities or Channels without permission.', penalty: '.blacklist and Level 3 .seize' },
    { num: 52, text: 'Group Call Spamming — Starting repeated group voice/video calls with no purpose or to annoy members.', penalty: '15-minute .mute and Level 2 .seize' },
    { num: 53, text: 'Unauthorized Group Calls — Initiating a group call without admin approval during quiet hours or events.', penalty: '10-minute .mute and .labor' },
    { num: 54, text: 'Spam Flooding — Sending more than 5 messages or stickers in 10 seconds.', penalty: '5-minute .mute and Level 1 .seize (Fine)' },
    { num: 55, text: 'Sticker Raiding — Sending massive amounts of stickers to lag phones.', penalty: '15-minute .mute and .exile' },
    { num: 56, text: 'Voice Note Spamming — Sending long, repetitive, or loud voice notes that disrupt the group.', penalty: '10-minute .mute and .labor' },
    { num: 57, text: 'Malicious Tagging — Using .tagall or tagging members repeatedly for no reason.', penalty: '5-minute .mute' },
    { num: 58, text: 'Tagging the Owner — Mentioning the bot owner or group creator for non-urgent matters.', penalty: '15-minute .mute' },
    { num: 59, text: 'Misuse of Bot Commands — Spamming bot triggers or using commands in the wrong context to disrupt the flow.', penalty: '10-minute .mute and .labor' },
    { num: 60, text: 'Poll Spamming — Creating multiple junk polls to flood the chat.', penalty: '5-minute .mute and Level 1 .seize' },
    { num: 61, text: 'Reaction Spam — Rapidly reacting to old messages to trigger notifications for everyone.', penalty: '3-minute .mute' },
    { num: 62, text: 'Forwarded Message Flooding — Dumping 5+ "forwarded many times" messages in under 1 minute.', penalty: '5-minute .mute and Level 1 .seize' },
    { num: 63, text: 'Contact Card Spam — Sharing random vCards/contact cards not related to group business.', penalty: '5-minute .mute' },
    { num: 64, text: 'Live Location Abuse — Dropping live location without context to spam or scare members.', penalty: '5-minute .mute and .labor' },
    { num: 65, text: 'Off Topic Violation — Discussing subjects strictly forbidden by the current group theme or pinned notice.', penalty: '5-minute .mute and Level 1 .seize' },
    { num: 66, text: 'Foreign Language Use — Typing in a language other than the group\'s official language without a translation.', penalty: '5-minute .mute and .labor' },
    { num: 67, text: 'Excessive Caps / Formatting Abuse — FULL CAPS or zalgo text to spam/bypass filters.', penalty: '3-minute .mute' },
    { num: 68, text: 'Deleting Messages — Deleting your own messages after sending them to hide evidence or disrupt conversation flow.', penalty: '.history mark and Level 1 .seize' },
    { num: 69, text: 'Vandalism — Proposing nonsense rules via .request to spam admins.', penalty: 'Level 1 .seize per nonsense request' },
    { num: 70, text: 'Gag Violation — Attempting to type while under a .mute order.', penalty: '3 warnings, then automatic .exile (Kick)' },
];
